name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      falkordb:
        image: falkordb/falkordb:latest
        ports:
          - 6379:6379
        options: > 
          --rm 
          -v ./data:/data

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Linux Packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install Python and Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3 \
            python3-pip \
            libmagic-dev \
            poppler-utils \
            tesseract-ocr \
            libreoffice

      - name: Install Python Requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run Tests
        run: python3 -m pytest

      - name: Install Pylint
        run: python3 -m pip install pylint

      - name: Run Linter with Pylint
        run: python3 -m pylint --exit-zero **/*.py

      - name: Test Main
        run: python3 main.py
